name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - DCR

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. 저장소의 최신 코드를 Runner로 가져옵니다.
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ywj/QA
            git pull origin DCR