name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - DCR

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code to server
        uses: actions/checkout@v4
        with:
          repository: ywj/QA
          ref: DCR
          path: /home/ywj/QA # 이 부분을 추가하여 코드를 원하는 경로에 가져오도록 합니다.